In [ ]:
# 모두의 딥러닝

In [ ]:
# 17장 딥러닝을 이용한 자연어 처리

In [ ]:
# 17-1 텍스트의 토큰화

In [2]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence, Tokenizer

In [3]:
text = '해보지 않으면 해낼 수 없다'
result = text_to_word_sequence(text)
print("\n원문:\n",text)
print("\n토큰화:\n", result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다,'
        ]

In [5]:
token =Tokenizer()
token.fit_on_texts(docs)

print('\n단어 카운트:\n', token.word_counts)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [6]:
print("\n문장 카운트: ", token.document_count)


문장 카운트:  3


In [7]:
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)


각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'나누어': 1, '먼저': 1, '토큰화합니다': 1, '텍스트의': 2, '단어를': 1, '각': 1, '토큰화해야': 1, '단어로': 1, '딥러닝에서': 2, '인식됩니다': 1, '있습니다': 1, '결과는': 1, '토큰화한': 1, '사용할': 1, '수': 1})


In [8]:
print("\n각 단어에 매겨진 인덱스 값:\n", token.word_index)


각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [9]:
# 17-2 단어의 원-핫 인코딩

In [12]:
text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [14]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [16]:
from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [17]:
# 17-3 단어 임배딩

In [18]:
# 단어 임베딩은 주어진 배열을 정해진 길이로 압축시킴

In [19]:
# 각 단어 간의 유사도를 계산하고 고려해 각 배열을 새로운 수치로 바꿔줌

In [20]:
# 17-4 텍스트를 읽고 긍정, 부정 예측하기 

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical

from numpy import array

In [25]:
docs = ["너무 재미있네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다", 
        "한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요",
        "연기가 어색해요","재미없어요"]

In [26]:
# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [27]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n", x)

{'너무': 1, '재미있네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [28]:
# 패딩(서로 다른 길이의 데이터를 4로 맞추어줌)
padded_x = pad_sequences(x,4)
print("\n패딩 결과:\n",padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [29]:
# 임베딩에 입력될 단어의 수 지정
word_size = len(token.word_index) + 1

In [33]:
# 단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_3 (Flatten)         (None, 32)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 1s 831ms/step - loss: 0.6849 - accuracy: 0.7000
Epoch 2/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6829 - accuracy: 0.8000
Epoch 3/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6810 - accuracy: 0.8000
Epoch 4/20
1/1 [==============